LoadModule mpm_event_module modules/mod_mpm_event.so

<IfModule mpm_event_module>
    StartServers             1
    ServerLimit              2
    ThreadsPerChild          15
    MaxRequestWorkers        30
    MaxConnectionsPerChild   0
</IfModule>